# Generated by Django 5.2.4 on 2025-08-05 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('purple', 'Purple')], max_length=10)),
                ('shape', models.CharField(choices=[('oval', 'Oval'), ('squiggle', 'Squiggle'), ('diamond', 'Diamond')], max_length=10)),
                ('count', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')])),
                ('fill', models.CharField(choices=[('open', 'Open'), ('striped', 'Striped'), ('solid', 'Solid')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
